[package]
name = "fft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
feather_m0 = { git = "https://github.com/atsamd-rs/atsamd" }
micromath = "2.0.0"
panic-halt = "0.2.0"

[dev-dependencies]
approx = "0.5.1"
criterion = "0.5.1"
random = "0.14.0"

[[bench]]
name = "array_bench"
harness = false
